name: Build macOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pillow pyinstaller

    - name: List files (查看当前目录文件)
      run: ls -la

    - name: Build macOS App
      run: |
        pyinstaller --onefile --windowed --clean main.py

    - name: Zip the App
      run: |
        cd dist
        zip -r ../CineMaster-macOS.zip main.app

    - name: Upload macOS App
      uses: actions/upload-artifact@v4
      with:
        name: CineMaster-macOS
        path: CineMaster-macOS.zip
